## ORDER ITEM [/order/{id}/item]

+ Parameters
    + id (required, number, `1`) - Order ID or current

### List [GET]

+ Response 404 (application/json)
+ Response 200 (application/json)

    + Attributes(OrderItemPager)

## ORDER ITEM Details [/order/{order_id}/item/{id}]

+ Parameters
    + order_id (required, number, `1`) - Order ID or current
    + id (required, number, `1`) - OrderItem ID

### Show [GET]

+ Response 200 (application/json)

    + Attributes(OrderItem)

### Edit [PUT]

+ Request (application/json)

    + Body
    
            {
                "quantity": 2 (number),
                "title": "Air Max" (string)
            }

+ Response 404 (application/json)
+ Response 200 (application/json)

    + Attributes(OrderItem)

### Delete [DELETE]

+ Response 404 (application/json)
+ Response 200 (application/json)