## Get Order Item details [/order/{order_id}/item/{id}]

+ Parameters
    + order_id (required, number, `1`) - Order ID or current
    + id (required, number, `1`) - OrderItem ID

### Get the order item [GET]

+ Response 200 (application/json)

    + Attributes(OrderItem)
    
### Modify order item [PUT]

+ Request (application/json)

    + Body
    
            {
                "quantity": 2 (number),
                "title": "Air Max" (string)
                "quantity": 2 (number)
            }

+ Response 404 (application/json)
+ Response 200 (application/json)

    + Attributes(OrderItem)