# Data Structures

## Pager

+ total: 4 (number)
+ per_page: 15 (number)
+ current_page: 1 (number)
+ last_page: 1 (number)
+ from: 1 (number)
+ to: 2 (number)

## UserPager (object)
+ Include Pager
+ data: User, User (array[User])

## OrderPager (object)

+ Include Pager
+ data: Order, Order (array[Order])

## OrderItemPager (object)

+ Include Pager
+ data: OrderItem, OrderItem (array[OrderItem])

## AddressPager (object)

+ Include Pager
+ data: Address, Address (array[Address])

## ReviewPager (object)

+ Include Pager
+ data: Review, Review (array[Review])

## ProductListingPager (object)

+ Include Pager
+ data: ProductListing, ProductListing (array[ProductListing])

## User (object)

+ id: 11212 (number)
+ first_name: `Teszt` (string)
+ last_name: `Elek` (string)
+ email: `elek.teszt@example.org` (string)
+ `email_confirmed_at`: `2017-01-01 01:01:01` (string)

## Review (object)

+ id: 1232 (number)
+ rating: 4 (number)
+ comment: `This is the best shoes ever` (string)
+ created_at: `2017-03-12T12:12:12` (string)

## Address (object)

+ id: 1232 (number)
+ title: `Budapesti cimem` (string)
+ country: `Magyarország` (string)
+ county: `Pest megye` (string)
+ city: `Budapest` (string)
+ street: `Fő utca 12. 3. em 2. ajtó` (string)
+ zip_code: `2345` (string)
+ customer_name: `Kovács Dezső vagy Cégnév kft.` (string)
+ vat: `HU12313133` (string)
+ phone_number: `+36 30 123 4567` (string)
+ comment: `Portán csengessen` (string)
+ is_default_shipping: false (boolean)
+ is_default_billing: false (boolean)

## ShippingAddress (object)

+ Include Address

## BillingAddress (object)

+ Include Address

## ShippingMethod (object)
+ slug: `gls`
+ title: `GLS futárszolgálat`
+ description: `Gyors, pontos, megbízható`
+ price
    + Include PriceDetail
    
## PaymentMethod (object)
+ slug: `card`
+ title: `Bankkártyás fizetés`
+ description: `Mastercard, Visa, Maestro`
+ price
    + Include PriceDetail

## Price (object)

+ value: 10 (number)
+ title: `10 Ft` (string)

## FullNetPrice (object)

+ net
    + Include Price
+ gross
    + Include Price

## PriceDetail

+ original
    + Include FullNetPrice
+ current
    + Include FullNetPrice

## ProductAttribute (object)

+ id: 111 (number)
+ slug: `color` (string)
+ title: `Szín` (string)
+ position: 1 (number)
+ value: `Fekete` (string) 

## ProductAttributeSet (object)

+ id: 111 (number)
+ slug: `cipo` (string)
+ title: `Cipő` (string)
+ attributes: ProductAttribute, ProductAttribute (array[ProductAttribute])







## ProductListing (object)

+ id: 123 (number)
+ title: `Air Max kezdő csomag` (string)
+ description: `Air Max kezdő csomag description` (string)
+ price
    + Include PriceDetail
+ option_groups: ProductOptionGroup, ProductOptionGroup (array[ProductOptionGroup])
+ products: ProductListingItem, ProductListingItem (array[ProductListingItem])
+ `can_be_ordered`: false (boolean)
+ `cannot_be_ordered_because`
    + `only_as_individual_items`: true (boolean)
+ recommended_product_listings (object)
    + product_listings: 

## ProductListingItem (object)

+ id: 111 (number)
+ sku: `4234hgh` (string)
+ title: `Air Max` (string)
+ description: `Air Max description` (string)
+ attributeSet: ProductAttribute, ProductAttribute (array[ProductAttribute])
+ options: ProductOption (array[ProductOption])
+ price
    + Include PriceDetail
+ `can_be_ordered`: true (boolean)
+ `cannot_be_ordered_because`
    + `only_as_bundle`: true (boolean)
    


















## ProductOption (object)

+ id: 111 (number)
+ slug: `size` (string)
+ title: `Size` (string)
+ value: `42` (string)

## ProductOptionGroup (object)
+ slug: `size` (string)
+ title: `Méret` (string)
+ ui_type: `select_one` (string)

## ImageThumbnails (object)
+ sizes
    + small
        + Include ImageThumbnailSize
    + medium
        + Include ImageThumbnailSize
    + large
        + Include ImageThumbnailSize
+ `is_placeholder`: false (boolean)

## ImageThumbnailSize (object)
+ `thumbnail_uri`: `https://fakeimg.pl/300/` (string)
+ `thumbnail_size`
    + `width`: `0` (number)
    + `height`: `0` (number)

## OrderItemUnit (object)

+ id: 111 (number)
+ title: `Air Max` (string)
+ options: ProductOption (array[ProductOption])
+ price
    + Include PriceDetail

## OrderItem (object)

+ id: 11212 (number)
+ title: `Air Max` (string)
+ quantity: 2 (number)
+ units: OrderItemUnit, OrderItemUnit (array[OrderItemUnit])
+ price
    + Include PriceDetail

## Order (object)

+ id: 11212 (number)
+ customer 
    + Include User
+ items: OrderItem, OrderItem, OrderItem (array[OrderItem])
+ status: `cart` (string)
+ customer_note: `This is a comment` (optional, string)
+ is_abandoned: false (boolean)
+ is_guest_customer: false (boolean)
+ total_quantity: 10 (number)
+ price
    + Include PriceDetail
+ shipping_method (optional)
    + Include ShippingMethod
+ payment_method (optional)
    + Include PaymentMethod
+ shipping_address (optional)
    + Include ShippingAddress
+ billing_address (optional)
    + Include BillingAddress