FORMAT: 1A
HOST: http://wo-man.apiblueprint.org

# Wo-man

Polls is a simple API allowing consumers to view polls and vote in them.

<!-- include(user.apib) -->
<!-- include(user/address.apib) -->
<!-- include(user/review.apib) -->
<!-- include(user/order.apib) -->

<!-- include(order.apib) -->
<!-- include(order/item.apib) -->
    
<!-- include(data-structures.apib) -->