## Order Collection [/order]

### List All Order [GET]

+ Response 200 (application/json)

    + Attributes(OrderPager)

## Get Order details [/order/{id}]

+ Parameters
    + id (required, number, `1`) - Order ID or current

### Get the order [GET]

+ Response 200 (application/json)

    + Attributes(Order)