## ORDER [/order]

### List [GET]

+ Response 200 (application/json)

    + Attributes(OrderPager)

## ORDER Details [/order/{id}]

+ Parameters
    + id (required, number, `1`) - Order ID or current

### Show [GET]

+ Response 200 (application/json)

    + Attributes(Order)
