## PRODUCT [/product{?search,page,per_page,order_by,order_by_direction}]

+ Parameters
    + search (optional, string, `air`) - Keyword
    + page (optional, number, `1`) - Requested Page Number
    + per_page (optional, number, `15`) - How many items per page
    + order_by (optional, string, `title`) - Product sort key 
    + order_by_direction (optional, string, `desc`) - Product order direction ascendant "asc" or descendant "desc"

### List / Search [GET]

+ Response 200 (application/json)

    + Attributes(ProductPager)

## PRODUCT Details [/product/{id}]

+ Parameters
    + id (required, number, `1`) - Product ID

### Show [GET]

+ Response 200 (application/json)

    + Attributes(Product)