## USER  [/user]

### List [GET]

+ Response 404 (application/json)
+ Response 200 (application/json)

    + Attributes(UserPager)
    
### Create [POST]

+ Request (application/json)

    + Body
    
            {
                "first_name": "Béla" (required, string),
                "last_name": "Kovács" (required, string),
                "email": "elek.teszt@example.org" (required, string),
                "password": "newpasword" (required, string),
                "newsletter": 1 (required, number)
            }

+ Response 201

    + Body

            {
                "token": "auth token"
            }
    
## USER Details [/user/{id}]

+ Parameters
    + id (required, number, `1`) - User ID or me

### Show [GET]

+ Response 200 (application/json)

    + Attributes(User)
    
### Edit [PUT]

+ Request (application/json)

    + Body
    
            {
                "first_name": "Béla" (string),
                "last_name": "Kovács" (string),
                "email": "elek.teszt@example.org" (string),
                "password": "newpasword" (optional, string)
            }

+ Response 200 (application/json)

    + Attributes(UserPager)