## User Order Collection / Cart Items [/user/{id}/order]

+ Parameters
    + id (required, number, `1`) - User ID or me

### List all orders of the user [GET]

+ Response 200 (application/json)

    + Attributes(OrderPager)